# -*- coding: utf-8 -*-
"""ANN Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gjus9Y2oKSTaWFkAZLeaov0WvEpAyuId

LOAN APPROVAL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/loan_data.csv")

df

df.isnull().sum()

X = df.drop(columns=['loan_status'])
y = df['loan_status']

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

selected_features = ['person_age', 'person_income', 'loan_amnt', 'credit_score', 'loan_status']

sns.pairplot(df[selected_features], hue='loan_status', palette='Set1', diag_kind='kde')
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#work flow
model = Sequential([
    Dense(units=32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(units=16, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, batch_size=32, epochs=30, validation_split=0.2)

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report

y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

print("Classification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Approved (0)', 'Rejected (1)'],
            yticklabels=['Approved (0)', 'Rejected (1)'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

model.save('loan_approval_ann.keras')

from tensorflow.keras.models import load_model
loaded_model = load_model('loan_approval_ann.keras')

model.summary()

sample_data = {
    'person_age': [28.0],
    'person_gender': ['male'],
    'person_education': ['Bachelor'],
    'person_income': [65000.0],
    'person_emp_exp': [4],
    'person_home_ownership': ['RENT'],
    'loan_amnt': [12000.0],
    'loan_intent': ['EDUCATION'],
    'loan_int_rate': [11.5],
    'loan_percent_income': [0.18],
    'cb_person_cred_hist_length': [5.0],
    'credit_score': [680],
    'previous_loan_defaults_on_file': ['No']
}

sample_df = pd.DataFrame(sample_data)

sample_encoded = pd.get_dummies(sample_df)
sample_encoded = sample_encoded.reindex(columns=X.columns, fill_value=0)

sample_scaled = scaler.transform(sample_encoded)

prob = model.predict(sample_scaled)[0][0]
prediction = 1 if prob > 0.5 else 0

print(f"Approval Probability: {prob:.4f}")
print(f"Predicted Class: {prediction} ({'Rejected' if prediction == 1 else 'Approved'})")

# Install gradio first if you haven't already: !pip install gradio
import gradio as gr


def predict_loan_status(
    person_age, person_gender, person_education, person_income,
    person_emp_exp, person_home_ownership, loan_amnt, loan_intent,
    loan_int_rate, loan_percent_income, cb_person_cred_hist_length,
    credit_score, previous_loan_defaults_on_file
):
    input_data = {
        'person_age': [float(person_age)],
        'person_gender': [person_gender],
        'person_education': [person_education],
        'person_income': [float(person_income)],
        'person_emp_exp': [int(person_emp_exp)],
        'person_home_ownership': [person_home_ownership],
        'loan_amnt': [float(loan_amnt)],
        'loan_intent': [loan_intent],
        'loan_int_rate': [float(loan_int_rate)],
        'loan_percent_income': [float(loan_percent_income)],
        'cb_person_cred_hist_length': [float(cb_person_cred_hist_length)],
        'credit_score': [int(credit_score)],
        'previous_loan_defaults_on_file': [previous_loan_defaults_on_file]
    }
    input_df = pd.DataFrame(input_data)

    input_encoded = pd.get_dummies(input_df)
    input_encoded = input_encoded.reindex(columns=X.columns, fill_value=0)

    input_scaled = scaler.transform(input_encoded)

    prob = model.predict(input_scaled)[0][0]

    status = "🔴 Rejected" if prob > 0.5 else "🟢 Approved"
    confidence = prob if prob > 0.5 else (1 - prob)

    return f"Decision: {status}\nConfidence Score: {confidence:.2%}"

interface = gr.Interface(
    fn=predict_loan_status,
    inputs=[
        gr.Number(label="Age", value=25),
        gr.Dropdown(choices=["male", "female"], label="Gender", value="male"),
        gr.Dropdown(choices=["High School", "Associate", "Bachelor", "Master", "Doctorate"], label="Education Level", value="Bachelor"),
        gr.Number(label="Annual Income ($)", value=50000),
        gr.Number(label="Employment Experience (Years)", value=3),
        gr.Dropdown(choices=["RENT", "MORTGAGE", "OWN", "OTHER"], label="Home Ownership", value="RENT"),
        gr.Number(label="Requested Loan Amount ($)", value=10000),
        gr.Dropdown(choices=["PERSONAL", "EDUCATION", "MEDICAL", "VENTURE", "HOMEIMPROVEMENT", "DEBTCONSOLIDATION"], label="Loan Intent", value="EDUCATION"),
        gr.Slider(minimum=0.0, maximum=25.0, step=0.1, label="Interest Rate (%)", value=11.5),
        gr.Slider(minimum=0.0, maximum=1.0, step=0.01, label="Loan Percent of Income (Ratio)", value=0.2),
        gr.Number(label="Credit History Length (Years)", value=5),
        gr.Number(label="Credit Score", value=650),
        gr.Dropdown(choices=["No", "Yes"], label="Previous Default on File?", value="No")
    ],
    outputs=gr.Textbox(label="Model Assessment Result"),
    title="🏦 Loan Approval Risk Assessment System",
    description="Enter the applicant's credentials below to compute an AI-driven prediction score for loan eligibility determination."
)

interface.launch(share=True)